name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - run: python3 -m venv venv
    - run: source venv/bin/activate
    - run: pip3 install -e .

    - run: python3 tests/call.py
    - run: python3 tests/loops.py
    - run: python3 tests/loops2.py
    - run: python3 tests/loops3.py
    - run: python3 tests/loops4.py
    - run: python3 tests/loops5.py
    - run: python3 tests/loops6.py
    - run: python3 tests/loops7.py
    - run: python3 tests/variable.py
    - run: python3 tests/comments.py
    - run: python3 tests/comments2.py
    - run: python3 tests/if_statement.py
    - run: python3 tests/if_statement2.py
